name: 'FNO.SVHN.DenseNet'
output_dir: './output/svhn'
valid_step: 1
save_step: -1
show_step: 100
input_size: (32, 32)
color_space: 'RGB'

dataset:
    root: '/data/anonymous'
    dataset: 'BalancedSVHN'
    num_classes: 10

backbone:
    type: 'densenets40_z'
    in_channels: 3

pooling:
    type: 'GlobalAvgPooling'

reshape:
    type: 'FlattenCustom'

classifier:
    type: 'OrthLiear'
    bias: False

scaling:
    type: 'Identity'

loss:
    loss_type: 'CrossEntropyCustom'

train:
    batch_size: 128
    num_epochs: 350
    num_workers: 2
    trainer:
        type: 'default'
    optimizer:
        type: 'SGD'
        base_lr: 0.06786
        weight_decay: 5e-4
    lr_scheduler:
        type: 'multistep'
        lr_factor: 0.1
        lr_step: [117, 233]
    tensorboard:
        enable: True

transforms:
    train_transforms: ('resize', 'normalize')
    test_transforms: ('resize', 'normalize')
    process_detail:
        resize: 32
        normalize:
            mean: [0.4377, 0.4439, 0.4731]
            std: [0.1974, 0.2005, 0.1968]

test:
    batch_size: 256
    num_workers: 2
    model_file: 'best_model.pth'

