name: 'CE.ImageNetLT.ResNet152.180epoch'
output_dir: './output/imbalanceimagenet'
valid_step: 1
save_step: -1
show_step: 100
input_size: (224, 224)
color_space: 'RGB'
cpu_mode: False
seed_num: 0
ddp: False
dp: True
mixed_precision: True

dataset:
    root: '/home/anonymous/data'
    dataset: 'ImageNetLT'
    type: 'imbalanced'
    num_classes: 1000
    imbalancecifar:
        ratio: 0.01
    class_index:
        many: [0, 390]
        med: [390, 835]
        few: [835, 1000]

backbone:
    type: 'resnet152_z'

pooling:
    type: 'GlobalAvgPooling'

reshape:
    type: 'FlattenCustom'

classifier:
    type: 'FC'
    bias: True

scaling:
    type: 'Identity'

loss:
    loss_type: 'CrossEntropyCustom'

train:
    batch_size: 256
    num_epochs: 180
    num_workers: 32
    trainer:
        type: 'default'
    optimizer:
        type: 'SGD'
        base_lr: 0.1
        weight_decay: 5e-4
        momentum: 0.9
    lr_scheduler:
        type: 'cosine'
        eta_min: 0.
    tensorboard:
        enable: True

transforms:
    train_transforms: ('random_resized_crop', 'random_horizontal_flip', 'normalize')
    test_transforms: ('resize', 'center_crop', 'normalize',)
    process_detail:
        resize: 256
        crop_size: 224
        normalize:
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]

test:
    batch_size: 256
    num_workers: 32
    model_file: 'best_model.pth'

