name: 'CE.FashionMNIST.ResNet'
output_dir: './output/fmnist'
valid_step: 1
save_step: -1
show_step: 100
input_size: (28, 28)
color_space: 'Gray'

dataset:
    root: '/data/anonymous'
    dataset: 'FashionMNIST'
    num_classes: 10

backbone:
    type: 'resnets18_z'
    in_channels: 1

pooling:
    type: 'GlobalAvgPooling'

reshape:
    type: 'FlattenCustom'

classifier:
    type: 'FC'
    bias: True

scaling:
    type: 'Identity'

loss:
    loss_type: 'CrossEntropyCustom'

train:
    batch_size: 128
    num_epochs: 350
    num_workers: 2
    trainer:
        type: 'default'
    optimizer:
        type: 'SGD'
        base_lr: 0.0001
        weight_decay: 5e-4
    lr_scheduler:
        type: 'multistep'
        lr_factor: 0.1
        lr_step: [117, 233]
    tensorboard:
        enable: True

transforms:
    train_transforms: ('resize', 'normalize')
    test_transforms: ('resize', 'normalize')
    process_detail:
        resize: 32
        normalize:
            mean: [0.286,]  # [0.2860,]
            std: [0.353,]  # [0.3530,]

test:
    batch_size: 256
    num_workers: 2
    model_file: 'best_model.pth'

